services:
  bigtable-emulator:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
    command: gcloud beta emulators bigtable start --host-port=0.0.0.0:8086
    ports:
      - "8086:8086"
